ci-merge: Allow running mergetool without X
Allow running mergetool in a non-windowing environment, by spawning
mergetool inline from the script. We no longer need to guess what terminal
might be installed on the system.

As the config file is fed line by line into the while loop we need to dup
the original stdin, or the spawned mergetool will read stdin from the
config file.

Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
[refactored to master]
Signed-off-by: Amit Kucheria <amit.kucheria@linaro.org>
Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

diff --git a/ci-merge b/ci-merge
--- a/ci-merge
+++ b/ci-merge
@@ -601,6 +601,9 @@ echo "Merging topic branches..."
 
 MERGED=0
 
+# Dup STDIN onto fd 3
+exec 3<&0
+
 while read LINE; do
 
     echo $LINE | egrep -q '(^#|^\s*$|^\s*\t*#)' && continue
@@ -626,15 +629,18 @@ while read LINE; do
                 exit $commit_ec
             fi
         else
-            echo "Merge failed, manual merge"
-            terminal -e "git mergetool -y"
-            git commit -a --no-edit
+	    echo "Merge failed, manual merge"
+	    git mergetool -y <&3 || exit
+	    git commit -a --no-edit
         fi
     fi
 
     MERGED=$((MERGED+1))
 
 done < $CONFIG
+
+# Close temporary STDIN clone
+exec 3<&-
 
 echo "Done, merged $MERGED topic(s)."
 
