ci-merge: handle the case of a dirty local git tree
We can't proceed with a local tree that has any changes. Either offer to
clean them out, or abort and let the user clean them.

Signed-off-by: Amit Kucheria <amit.kucheria@linaro.org>
Signed-off-by: Daniel Lezcano <daniel.lezcano@free.fr>

diff --git a/ci-merge b/ci-merge
--- a/ci-merge
+++ b/ci-merge
@@ -284,6 +284,30 @@ baseline_branch_setup() {
 
 ######################################################################
 #
+# Ensure that the local repo is clean
+#
+clean_local_repo() {
+    if [[ $(git status --porcelain) ]]; then
+	# Changes
+	echo "Local changes present"
+	git status --porcelain
+	echo -n "Clean it [Y/n]? "
+	read RES
+	if [ "$RES" == "Y" -o "$RES" == "y" -o "$RES" == "" ]; then
+	    git clean -df
+	    git reset --hard
+	else
+	    echo "Please clean the repo before proceeding. Aborting."
+	    exit 1
+	fi
+    else
+       # No changes
+       echo "Local tree is clean"
+    fi
+}
+
+######################################################################
+#
 # This is the global setup entry calling the different setup functions.
 # It ensures they are called in the right order.
 # !! Make sure to not change the order without double checking the !!
@@ -300,6 +324,8 @@ do_setup() {
     config_setup
 
     baseline_branch_setup
+
+    clean_local_repo
 }
 
 ######################################################################
