ci-merge: When a merge conflict exists try to commit
Used to handle when a merge conflict is resolved by rerere
should be ok to commit without any edit/add.

Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>
Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

diff --git a/ci-merge b/ci-merge
--- a/ci-merge
+++ b/ci-merge
@@ -573,8 +573,12 @@ while read LINE; do
     git merge -q --no-ff --no-edit $REMOTE_NAME/$REMOTE_BRANCH
     if [ $? -ne 0 ]; then
         if [ -z $DISPLAY ]; then
-            echo "Merge failed, $REMOTE_NAME $REMOTE_URL $REMOTE_BRANCH"
-            git merge --abort
+            # try to commit, may be resolved by rerere
+            git commit --no-edit
+            if [ $? -ne 0 ]; then
+                echo "Merge failed, $REMOTE_NAME $REMOTE_URL $REMOTE_BRANCH"
+                git merge --abort
+            fi
         else
             echo "Merge failed, manual merge"
             terminal -e "git mergetool -y"
